/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as ContentRouteImport } from './routes/content'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as MediaRouteImport } from './routes/media'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as RedirectsRouteImport } from './routes/redirects'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SeoRouteImport } from './routes/seo'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TaxonomyRouteImport } from './routes/taxonomy'
import { Route as TeamRouteImport } from './routes/team'
import { Route as BlogIdRouteImport } from './routes/blog.$id'
import { Route as ContentIndexRouteImport } from './routes/content.index'
import { Route as ContentIdRouteImport } from './routes/content.$id'
import { Route as ContentNewRouteImport } from './routes/content.new'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as JournalAcademyRouteImport } from './routes/journal.academy'
import { Route as JournalArticlesRouteImport } from './routes/journal.articles'
import { Route as JournalCaseStudiesRouteImport } from './routes/journal.case-studies'
import { Route as JournalResourcesRouteImport } from './routes/journal.resources'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnSlugRouteImport } from './routes/learn.$slug'
import { Route as JournalAcademySlugRouteImport } from './routes/journal.academy.$slug'
import { Route as JournalArticlesSlugRouteImport } from './routes/journal.articles.$slug'
import { Route as JournalCaseStudiesSlugRouteImport } from './routes/journal.case-studies.$slug'
import { Route as JournalResourcesSlugRouteImport } from './routes/journal.resources.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const RedirectsRoute = RedirectsRouteImport.update({
  id: '/redirects',
  path: '/redirects',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoRoute = SeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxonomyRoute = TaxonomyRouteImport.update({
  id: '/taxonomy',
  path: '/taxonomy',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIdRoute = BlogIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BlogRoute,
} as any)
const ContentIndexRoute = ContentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContentRoute,
} as any)
const ContentIdRoute = ContentIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ContentRoute,
} as any)
const ContentNewRoute = ContentNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ContentRoute,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JournalRoute,
} as any)
const JournalAcademyRoute = JournalAcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => JournalRoute,
} as any)
const JournalArticlesRoute = JournalArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => JournalRoute,
} as any)
const JournalCaseStudiesRoute = JournalCaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => JournalRoute,
} as any)
const JournalResourcesRoute = JournalResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => JournalRoute,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnRoute,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LearnRoute,
} as any)
const JournalAcademySlugRoute = JournalAcademySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JournalAcademyRoute,
} as any)
const JournalArticlesSlugRoute = JournalArticlesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JournalArticlesRoute,
} as any)
const JournalCaseStudiesSlugRoute = JournalCaseStudiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JournalCaseStudiesRoute,
} as any)
const JournalResourcesSlugRoute = JournalResourcesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JournalResourcesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/architecture': typeof ArchitectureRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/case-studies': typeof CaseStudiesRoute
  '/content': typeof ContentRouteWithChildren
  '/docs': typeof DocsRoute
  '/integrations': typeof IntegrationsRoute
  '/journal': typeof JournalRouteWithChildren
  '/landing': typeof LandingRoute
  '/learn': typeof LearnRouteWithChildren
  '/media': typeof MediaRoute
  '/newsletter': typeof NewsletterRoute
  '/redirects': typeof RedirectsRoute
  '/resources': typeof ResourcesRoute
  '/seo': typeof SeoRoute
  '/settings': typeof SettingsRoute
  '/taxonomy': typeof TaxonomyRoute
  '/team': typeof TeamRoute
  '/blog/$id': typeof BlogIdRoute
  '/content/$id': typeof ContentIdRoute
  '/content/new': typeof ContentNewRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/journal/academy': typeof JournalAcademyRouteWithChildren
  '/journal/articles': typeof JournalArticlesRouteWithChildren
  '/journal/case-studies': typeof JournalCaseStudiesRouteWithChildren
  '/journal/resources': typeof JournalResourcesRouteWithChildren
  '/learn/$slug': typeof LearnSlugRoute
  '/content/': typeof ContentIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/journal/academy/$slug': typeof JournalAcademySlugRoute
  '/journal/articles/$slug': typeof JournalArticlesSlugRoute
  '/journal/case-studies/$slug': typeof JournalCaseStudiesSlugRoute
  '/journal/resources/$slug': typeof JournalResourcesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/architecture': typeof ArchitectureRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/case-studies': typeof CaseStudiesRoute
  '/docs': typeof DocsRoute
  '/integrations': typeof IntegrationsRoute
  '/journal': typeof JournalRouteWithChildren
  '/landing': typeof LandingRoute
  '/media': typeof MediaRoute
  '/newsletter': typeof NewsletterRoute
  '/redirects': typeof RedirectsRoute
  '/resources': typeof ResourcesRoute
  '/seo': typeof SeoRoute
  '/settings': typeof SettingsRoute
  '/taxonomy': typeof TaxonomyRoute
  '/team': typeof TeamRoute
  '/blog/$id': typeof BlogIdRoute
  '/content/$id': typeof ContentIdRoute
  '/content/new': typeof ContentNewRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/journal/academy': typeof JournalAcademyRouteWithChildren
  '/journal/articles': typeof JournalArticlesRouteWithChildren
  '/journal/case-studies': typeof JournalCaseStudiesRouteWithChildren
  '/journal/resources': typeof JournalResourcesRouteWithChildren
  '/learn/$slug': typeof LearnSlugRoute
  '/content': typeof ContentIndexRoute
  '/learn': typeof LearnIndexRoute
  '/journal/academy/$slug': typeof JournalAcademySlugRoute
  '/journal/articles/$slug': typeof JournalArticlesSlugRoute
  '/journal/case-studies/$slug': typeof JournalCaseStudiesSlugRoute
  '/journal/resources/$slug': typeof JournalResourcesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/architecture': typeof ArchitectureRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/case-studies': typeof CaseStudiesRoute
  '/content': typeof ContentRouteWithChildren
  '/docs': typeof DocsRoute
  '/integrations': typeof IntegrationsRoute
  '/journal': typeof JournalRouteWithChildren
  '/landing': typeof LandingRoute
  '/learn': typeof LearnRouteWithChildren
  '/media': typeof MediaRoute
  '/newsletter': typeof NewsletterRoute
  '/redirects': typeof RedirectsRoute
  '/resources': typeof ResourcesRoute
  '/seo': typeof SeoRoute
  '/settings': typeof SettingsRoute
  '/taxonomy': typeof TaxonomyRoute
  '/team': typeof TeamRoute
  '/blog/$id': typeof BlogIdRoute
  '/content/$id': typeof ContentIdRoute
  '/content/new': typeof ContentNewRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/journal/academy': typeof JournalAcademyRouteWithChildren
  '/journal/articles': typeof JournalArticlesRouteWithChildren
  '/journal/case-studies': typeof JournalCaseStudiesRouteWithChildren
  '/journal/resources': typeof JournalResourcesRouteWithChildren
  '/learn/$slug': typeof LearnSlugRoute
  '/content/': typeof ContentIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/journal/academy/$slug': typeof JournalAcademySlugRoute
  '/journal/articles/$slug': typeof JournalArticlesSlugRoute
  '/journal/case-studies/$slug': typeof JournalCaseStudiesSlugRoute
  '/journal/resources/$slug': typeof JournalResourcesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academy'
    | '/admin'
    | '/analytics'
    | '/architecture'
    | '/auth'
    | '/blog'
    | '/case-studies'
    | '/content'
    | '/docs'
    | '/integrations'
    | '/journal'
    | '/landing'
    | '/learn'
    | '/media'
    | '/newsletter'
    | '/redirects'
    | '/resources'
    | '/seo'
    | '/settings'
    | '/taxonomy'
    | '/team'
    | '/blog/$id'
    | '/content/$id'
    | '/content/new'
    | '/journal/$slug'
    | '/journal/academy'
    | '/journal/articles'
    | '/journal/case-studies'
    | '/journal/resources'
    | '/learn/$slug'
    | '/content/'
    | '/learn/'
    | '/journal/academy/$slug'
    | '/journal/articles/$slug'
    | '/journal/case-studies/$slug'
    | '/journal/resources/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academy'
    | '/admin'
    | '/analytics'
    | '/architecture'
    | '/auth'
    | '/blog'
    | '/case-studies'
    | '/docs'
    | '/integrations'
    | '/journal'
    | '/landing'
    | '/media'
    | '/newsletter'
    | '/redirects'
    | '/resources'
    | '/seo'
    | '/settings'
    | '/taxonomy'
    | '/team'
    | '/blog/$id'
    | '/content/$id'
    | '/content/new'
    | '/journal/$slug'
    | '/journal/academy'
    | '/journal/articles'
    | '/journal/case-studies'
    | '/journal/resources'
    | '/learn/$slug'
    | '/content'
    | '/learn'
    | '/journal/academy/$slug'
    | '/journal/articles/$slug'
    | '/journal/case-studies/$slug'
    | '/journal/resources/$slug'
  id:
    | '__root__'
    | '/'
    | '/academy'
    | '/admin'
    | '/analytics'
    | '/architecture'
    | '/auth'
    | '/blog'
    | '/case-studies'
    | '/content'
    | '/docs'
    | '/integrations'
    | '/journal'
    | '/landing'
    | '/learn'
    | '/media'
    | '/newsletter'
    | '/redirects'
    | '/resources'
    | '/seo'
    | '/settings'
    | '/taxonomy'
    | '/team'
    | '/blog/$id'
    | '/content/$id'
    | '/content/new'
    | '/journal/$slug'
    | '/journal/academy'
    | '/journal/articles'
    | '/journal/case-studies'
    | '/journal/resources'
    | '/learn/$slug'
    | '/content/'
    | '/learn/'
    | '/journal/academy/$slug'
    | '/journal/articles/$slug'
    | '/journal/case-studies/$slug'
    | '/journal/resources/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademyRoute: typeof AcademyRoute
  AdminRoute: typeof AdminRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ArchitectureRoute: typeof ArchitectureRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContentRoute: typeof ContentRouteWithChildren
  DocsRoute: typeof DocsRoute
  IntegrationsRoute: typeof IntegrationsRoute
  JournalRoute: typeof JournalRouteWithChildren
  LandingRoute: typeof LandingRoute
  LearnRoute: typeof LearnRouteWithChildren
  MediaRoute: typeof MediaRoute
  NewsletterRoute: typeof NewsletterRoute
  RedirectsRoute: typeof RedirectsRoute
  ResourcesRoute: typeof ResourcesRoute
  SeoRoute: typeof SeoRoute
  SettingsRoute: typeof SettingsRoute
  TaxonomyRoute: typeof TaxonomyRoute
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redirects': {
      id: '/redirects'
      path: '/redirects'
      fullPath: '/redirects'
      preLoaderRoute: typeof RedirectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo': {
      id: '/seo'
      path: '/seo'
      fullPath: '/seo'
      preLoaderRoute: typeof SeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taxonomy': {
      id: '/taxonomy'
      path: '/taxonomy'
      fullPath: '/taxonomy'
      preLoaderRoute: typeof TaxonomyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$id': {
      id: '/blog/$id'
      path: '/$id'
      fullPath: '/blog/$id'
      preLoaderRoute: typeof BlogIdRouteImport
      parentRoute: typeof BlogRoute
    }
    '/content/': {
      id: '/content/'
      path: '/'
      fullPath: '/content/'
      preLoaderRoute: typeof ContentIndexRouteImport
      parentRoute: typeof ContentRoute
    }
    '/content/$id': {
      id: '/content/$id'
      path: '/$id'
      fullPath: '/content/$id'
      preLoaderRoute: typeof ContentIdRouteImport
      parentRoute: typeof ContentRoute
    }
    '/content/new': {
      id: '/content/new'
      path: '/new'
      fullPath: '/content/new'
      preLoaderRoute: typeof ContentNewRouteImport
      parentRoute: typeof ContentRoute
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof JournalRoute
    }
    '/journal/academy': {
      id: '/journal/academy'
      path: '/academy'
      fullPath: '/journal/academy'
      preLoaderRoute: typeof JournalAcademyRouteImport
      parentRoute: typeof JournalRoute
    }
    '/journal/articles': {
      id: '/journal/articles'
      path: '/articles'
      fullPath: '/journal/articles'
      preLoaderRoute: typeof JournalArticlesRouteImport
      parentRoute: typeof JournalRoute
    }
    '/journal/case-studies': {
      id: '/journal/case-studies'
      path: '/case-studies'
      fullPath: '/journal/case-studies'
      preLoaderRoute: typeof JournalCaseStudiesRouteImport
      parentRoute: typeof JournalRoute
    }
    '/journal/resources': {
      id: '/journal/resources'
      path: '/resources'
      fullPath: '/journal/resources'
      preLoaderRoute: typeof JournalResourcesRouteImport
      parentRoute: typeof JournalRoute
    }
    '/learn/': {
      id: '/learn/'
      path: '/'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof LearnRoute
    }
    '/journal/academy/$slug': {
      id: '/journal/academy/$slug'
      path: '/$slug'
      fullPath: '/journal/academy/$slug'
      preLoaderRoute: typeof JournalAcademySlugRouteImport
      parentRoute: typeof JournalAcademyRoute
    }
    '/journal/articles/$slug': {
      id: '/journal/articles/$slug'
      path: '/$slug'
      fullPath: '/journal/articles/$slug'
      preLoaderRoute: typeof JournalArticlesSlugRouteImport
      parentRoute: typeof JournalArticlesRoute
    }
    '/journal/case-studies/$slug': {
      id: '/journal/case-studies/$slug'
      path: '/$slug'
      fullPath: '/journal/case-studies/$slug'
      preLoaderRoute: typeof JournalCaseStudiesSlugRouteImport
      parentRoute: typeof JournalCaseStudiesRoute
    }
    '/journal/resources/$slug': {
      id: '/journal/resources/$slug'
      path: '/$slug'
      fullPath: '/journal/resources/$slug'
      preLoaderRoute: typeof JournalResourcesSlugRouteImport
      parentRoute: typeof JournalResourcesRoute
    }
  }
}

interface BlogRouteChildren {
  BlogIdRoute: typeof BlogIdRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogIdRoute: BlogIdRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ContentRouteChildren {
  ContentIdRoute: typeof ContentIdRoute
  ContentNewRoute: typeof ContentNewRoute
  ContentIndexRoute: typeof ContentIndexRoute
}

const ContentRouteChildren: ContentRouteChildren = {
  ContentIdRoute: ContentIdRoute,
  ContentNewRoute: ContentNewRoute,
  ContentIndexRoute: ContentIndexRoute,
}

const ContentRouteWithChildren =
  ContentRoute._addFileChildren(ContentRouteChildren)

interface JournalAcademyRouteChildren {
  JournalAcademySlugRoute: typeof JournalAcademySlugRoute
}

const JournalAcademyRouteChildren: JournalAcademyRouteChildren = {
  JournalAcademySlugRoute: JournalAcademySlugRoute,
}

const JournalAcademyRouteWithChildren = JournalAcademyRoute._addFileChildren(
  JournalAcademyRouteChildren,
)

interface JournalArticlesRouteChildren {
  JournalArticlesSlugRoute: typeof JournalArticlesSlugRoute
}

const JournalArticlesRouteChildren: JournalArticlesRouteChildren = {
  JournalArticlesSlugRoute: JournalArticlesSlugRoute,
}

const JournalArticlesRouteWithChildren = JournalArticlesRoute._addFileChildren(
  JournalArticlesRouteChildren,
)

interface JournalCaseStudiesRouteChildren {
  JournalCaseStudiesSlugRoute: typeof JournalCaseStudiesSlugRoute
}

const JournalCaseStudiesRouteChildren: JournalCaseStudiesRouteChildren = {
  JournalCaseStudiesSlugRoute: JournalCaseStudiesSlugRoute,
}

const JournalCaseStudiesRouteWithChildren =
  JournalCaseStudiesRoute._addFileChildren(JournalCaseStudiesRouteChildren)

interface JournalResourcesRouteChildren {
  JournalResourcesSlugRoute: typeof JournalResourcesSlugRoute
}

const JournalResourcesRouteChildren: JournalResourcesRouteChildren = {
  JournalResourcesSlugRoute: JournalResourcesSlugRoute,
}

const JournalResourcesRouteWithChildren =
  JournalResourcesRoute._addFileChildren(JournalResourcesRouteChildren)

interface JournalRouteChildren {
  JournalSlugRoute: typeof JournalSlugRoute
  JournalAcademyRoute: typeof JournalAcademyRouteWithChildren
  JournalArticlesRoute: typeof JournalArticlesRouteWithChildren
  JournalCaseStudiesRoute: typeof JournalCaseStudiesRouteWithChildren
  JournalResourcesRoute: typeof JournalResourcesRouteWithChildren
}

const JournalRouteChildren: JournalRouteChildren = {
  JournalSlugRoute: JournalSlugRoute,
  JournalAcademyRoute: JournalAcademyRouteWithChildren,
  JournalArticlesRoute: JournalArticlesRouteWithChildren,
  JournalCaseStudiesRoute: JournalCaseStudiesRouteWithChildren,
  JournalResourcesRoute: JournalResourcesRouteWithChildren,
}

const JournalRouteWithChildren =
  JournalRoute._addFileChildren(JournalRouteChildren)

interface LearnRouteChildren {
  LearnSlugRoute: typeof LearnSlugRoute
  LearnIndexRoute: typeof LearnIndexRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnSlugRoute: LearnSlugRoute,
  LearnIndexRoute: LearnIndexRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademyRoute: AcademyRoute,
  AdminRoute: AdminRoute,
  AnalyticsRoute: AnalyticsRoute,
  ArchitectureRoute: ArchitectureRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  CaseStudiesRoute: CaseStudiesRoute,
  ContentRoute: ContentRouteWithChildren,
  DocsRoute: DocsRoute,
  IntegrationsRoute: IntegrationsRoute,
  JournalRoute: JournalRouteWithChildren,
  LandingRoute: LandingRoute,
  LearnRoute: LearnRouteWithChildren,
  MediaRoute: MediaRoute,
  NewsletterRoute: NewsletterRoute,
  RedirectsRoute: RedirectsRoute,
  ResourcesRoute: ResourcesRoute,
  SeoRoute: SeoRoute,
  SettingsRoute: SettingsRoute,
  TaxonomyRoute: TaxonomyRoute,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
